"""
add_recurring_transactions_and_account_balance

Revision ID: 8926f65b9f8a
Revises: 2e744227fd92
Create Date: 2026-01-28 21:19:31.497474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8926f65b9f8a"
down_revision: Union[str, Sequence[str], None] = "2e744227fd92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # 1. Safely handle the Enums first (The "Safety Net")
    # This prevents the "already exists" and "does not exist" errors.
    frequency_enum = postgresql.ENUM("DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="frequency")
    frequency_enum.create(bind, checkfirst=True)

    status_enum = postgresql.ENUM("PENDING", "COMPLETED", "CANCELLED", name="expensestatus")
    status_enum.create(bind, checkfirst=True)

    # 2. Create the new tables
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "emoji", name="uq_exp_emoji_per_account"),
        sa.UniqueConstraint("account_id", "name", name="uq_exp_category_per_account"),
        sa.UniqueConstraint("id"),
    )

    op.create_table(
        "recurring_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("frequency", sa.Enum(name="frequency", native_enum=False), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("next_occurrence_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("icon", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "icon", name="uq_exp_icon_per_account"),
        sa.UniqueConstraint("account_id", "name", name="uq_recurring_name_per_account"),
        sa.UniqueConstraint("id"),
    )

    # 3. Update existing tables
    op.add_column("accounts", sa.Column("default_category_id", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "accounts", ["id"])
    op.create_foreign_key(
        "fk_account_default_category", "accounts", "categories", ["default_category_id"], ["id"], use_alter=True
    )

    op.add_column("expenses", sa.Column("category_id", sa.UUID(), nullable=False))
    op.add_column("expenses", sa.Column("status", sa.Enum(name="expensestatus", native_enum=False), nullable=False))

    # 4. Cleanup and Indexes
    op.drop_index(op.f("ix_expenses_account_category"), table_name="expenses")
    op.create_index("ix_expenses_account_category", "expenses", ["account_id", "category_id"], unique=False)
    op.create_foreign_key(None, "expenses", "categories", ["category_id"], ["id"])
    op.drop_column("expenses", "category")
    op.create_unique_constraint(None, "memberships", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "memberships", type_="unique")
    op.add_column(
        "expenses",
        sa.Column(
            "category",
            postgresql.ENUM(
                "RENTAL",
                "BILLS",
                "GROCERIES",
                "HOUSEHOLD",
                "DELIVERY_FOOD",
                "DINING_OUT",
                "PET",
                "GAS",
                "CAR",
                "TRAVEL",
                "ENTERTAINMENT",
                "HEALTH",
                "PERSONAL",
                "SAVINGS",
                "MISC",
                name="expensecategory",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.drop_index("ix_expenses_account_category", table_name="expenses")
    op.create_index(op.f("ix_expenses_account_category"), "expenses", ["account_id", "category"], unique=False)
    op.drop_column("expenses", "status")
    op.drop_column("expenses", "category_id")
    op.drop_constraint("fk_account_default_category", "accounts", type_="foreignkey")
    op.drop_constraint(None, "accounts", type_="unique")
    op.drop_column("accounts", "default_category_id")
    op.drop_table("recurring_templates")
    op.drop_table("categories")
    # ### end Alembic commands ###
